/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppToolsRouteImport } from './routes/_app.tools'
import { Route as AppPcbRouteImport } from './routes/_app.pcb'
import { Route as AppGeneratorRouteImport } from './routes/_app.generator'
import { Route as AppElectronicsRouteImport } from './routes/_app.electronics'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAnalyserRouteImport } from './routes/_app.analyser'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppChatIndexRouteImport } from './routes/_app.chat.index'
import { Route as AppChatThreadIdRouteImport } from './routes/_app.chat.$threadId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppPcbRoute = AppPcbRouteImport.update({
  id: '/pcb',
  path: '/pcb',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratorRoute = AppGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AppRoute,
} as any)
const AppElectronicsRoute = AppElectronicsRouteImport.update({
  id: '/electronics',
  path: '/electronics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyserRoute = AppAnalyserRouteImport.update({
  id: '/analyser',
  path: '/analyser',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRoute,
} as any)
const AppChatThreadIdRoute = AppChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AppAdminRoute
  '/analyser': typeof AppAnalyserRoute
  '/chat': typeof AppChatRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/electronics': typeof AppElectronicsRoute
  '/generator': typeof AppGeneratorRoute
  '/pcb': typeof AppPcbRoute
  '/tools': typeof AppToolsRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/chat/': typeof AppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AppAdminRoute
  '/analyser': typeof AppAnalyserRoute
  '/dashboard': typeof AppDashboardRoute
  '/electronics': typeof AppElectronicsRoute
  '/generator': typeof AppGeneratorRoute
  '/pcb': typeof AppPcbRoute
  '/tools': typeof AppToolsRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/chat': typeof AppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/analyser': typeof AppAnalyserRoute
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/electronics': typeof AppElectronicsRoute
  '/_app/generator': typeof AppGeneratorRoute
  '/_app/pcb': typeof AppPcbRoute
  '/_app/tools': typeof AppToolsRoute
  '/_app/chat/$threadId': typeof AppChatThreadIdRoute
  '/_app/chat/': typeof AppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/pricing'
    | '/admin'
    | '/analyser'
    | '/chat'
    | '/dashboard'
    | '/electronics'
    | '/generator'
    | '/pcb'
    | '/tools'
    | '/chat/$threadId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/pricing'
    | '/admin'
    | '/analyser'
    | '/dashboard'
    | '/electronics'
    | '/generator'
    | '/pcb'
    | '/tools'
    | '/chat/$threadId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/login'
    | '/pricing'
    | '/_app/admin'
    | '/_app/analyser'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/electronics'
    | '/_app/generator'
    | '/_app/pcb'
    | '/_app/tools'
    | '/_app/chat/$threadId'
    | '/_app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcb': {
      id: '/_app/pcb'
      path: '/pcb'
      fullPath: '/pcb'
      preLoaderRoute: typeof AppPcbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generator': {
      id: '/_app/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AppGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/electronics': {
      id: '/_app/electronics'
      path: '/electronics'
      fullPath: '/electronics'
      preLoaderRoute: typeof AppElectronicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analyser': {
      id: '/_app/analyser'
      path: '/analyser'
      fullPath: '/analyser'
      preLoaderRoute: typeof AppAnalyserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/chat/$threadId': {
      id: '/_app/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AppChatThreadIdRouteImport
      parentRoute: typeof AppChatRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatThreadIdRoute: typeof AppChatThreadIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatThreadIdRoute: AppChatThreadIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyserRoute: typeof AppAnalyserRoute
  AppChatRoute: typeof AppChatRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppElectronicsRoute: typeof AppElectronicsRoute
  AppGeneratorRoute: typeof AppGeneratorRoute
  AppPcbRoute: typeof AppPcbRoute
  AppToolsRoute: typeof AppToolsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyserRoute: AppAnalyserRoute,
  AppChatRoute: AppChatRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppElectronicsRoute: AppElectronicsRoute,
  AppGeneratorRoute: AppGeneratorRoute,
  AppPcbRoute: AppPcbRoute,
  AppToolsRoute: AppToolsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
